<?php

/**
 * @var \Sapient\AccessWorldpay\Block\Jwt $block
 */
$params = $block->getRequest()->getParams();
$ccNumber = '';
if ($params) {
    $ccNumber = str_replace(' ', '+', $params['instrument']);
}
$ddcUrl = $block->getDdcUrl();
$jwt = $block->getJWT();
?>

<form method="post" action="<?= /* @noEscape */ $ddcUrl;?>" id="collectionForm" name="collectionForm"> 
    <input type="hidden" name="Bin" id="first_bin" value="" />
    <input type="hidden" name="JWT" id="first_jwt" value="" />
</form>

<script src="//cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/hmac-sha256.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/enc-base64-min.js"></script>
<script language="Javascript">
    //Decrypt bin number
    var cNum = "<?= /* @noEscape */ $ccNumber?>";
    var decodedBin = atob(cNum);
    document.getElementById("first_bin").value = decodedBin;
 
   var encodedJWT = "<?= /* @noEscape */ $jwt;?>";
    
    document.getElementById("first_jwt").value = encodedJWT;

    window.onload = function()
    {
      // Auto submit form on page load
      document.getElementById("collectionForm").submit();
    }

</script>