<?php  $_savecards=$block->getSavedCard(); ?>
<?= /* @noEscape */ $block->getChildHtml('info');?>
<?php if ($_savecards && count($_savecards)): ?>
    <div class="table-wrapper saved-cards">
        <table class="data table table-savedcard-items history" id="my-savecards-table">
            <caption class="table-caption"><?= /* @noEscape */__('Saved Cards') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col brand"><?= /* @noEscape */ $block->getMyAccountLabels('AC2') ?
                                $block->getMyAccountLabels('AC2') : 'Card Brand' ?></th>
                    <th scope="col" class="col date"><?= /* @noEscape */ $block->getMyAccountLabels('AC3') ?
                                $block->getMyAccountLabels('AC3') : 'Card Number' ?></th>
                    <th scope="col" class="col shipping"><?= /* @noEscape */ $block->getMyAccountLabels('AC1') ?
                                $block->getMyAccountLabels('AC1') : 'Card Holder Name' ?></th>
                    <th scope="col" class="col total"><?= /* @noEscape */ $block->getMyAccountLabels('AC4') ?
                                $block->getMyAccountLabels('AC4') : 'Card Expiry Month' ?></th>
                    <th scope="col" class="col status"><?= /* @noEscape */ $block->getMyAccountLabels('AC5') ?
                                $block->getMyAccountLabels('AC5') : 'Card Expiry Year' ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_savecards as $_savecard): ?>
                    <tr>
                        <td data-th="<?= /* @noEscape */ $block->getMyAccountLabels('AC2') ?
                                $block->getMyAccountLabels('AC2') : 'Card Brand' ?>"
                               class="col date"><?= /* @noEscape */ $_savecard->getCardBrand() ?>
                           </td>
                           <td data-th="<?= /* @noEscape */ $block->getMyAccountLabels('AC3') ?
                                $block->getMyAccountLabels('AC3') : 'Card Number' ?>"
                               class="col date"><?= /* @noEscape */ $_savecard->getCardNumber() ?>
                           </td>
                        <td data-th="<?= /* @noEscape */ $block->getMyAccountLabels('AC1') ?
                                $block->getMyAccountLabels('AC1') : 'Card Holder Name' ?>"
                            class="col shipping"><?= /* @noEscape */ $_savecard->getCardholderName() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */$block->getMyAccountLabels('AC4') ?
                                $block->getMyAccountLabels('AC4') : 'Card Expiry Month' ?>"
                            class="col total"><?= /* @noEscape */ $_savecard->getCardExpiryMonth() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */$block->getMyAccountLabels('AC5') ?
                                $block->getMyAccountLabels('AC5') : 'Card Expiry Year' ?>"
                            class="col status"><?= /* @noEscape */ $_savecard->getCardExpiryYear() ?>
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                           
                              <?php
                                if ($_savecard->getTokenId() != '') {
                                    ?>
                            <a href="<?= /* @noEscape */ $block->getEditUrl($_savecard) ?>" class="action view">
                                <span><?= /* @noEscape */ $block->getMyAccountLabels('AC6') ?
                                $block->getMyAccountLabels('AC6') : 'Update' ?></span>
                            </a>
                                    <?php
                                }
                                ?>
                            
                        </td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="javascript:void(0)" data-delete-url="
                        <?= /* @noEscape */ $block->getDeleteUrl($_savecard); ?>" class="action delete">
                            <span><?= /* @noEscape */ $block->getMyAccountLabels('AC10') ?
                                $block->getMyAccountLabels('AC10') : 'Delete' ?></span></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
            require([
                'jquery',
                'Magento_Ui/js/modal/confirm'
            ], function($, confirm) {
                $(".action.delete").on("click", function(event) {   
                    confirm({
                        title: 'Delete',
                        content: 'Are you sure you want to delete the card? \n\
                        Once the card is deleted, subscriptions associated with it will be cancelled!!!',
                        actions: {
                            confirm: function() {
                                window.location.href = $(event.currentTarget).data('delete-url');
                            }
                        }
                    });
                });
            });
        </script>
    </div>
<?php else: ?>
    <div class="message info empty">
        <span><?= /* @noEscape */ $block->getMyAccountLabels('AC19') ?
                                $block->getMyAccountLabels('AC19') : 'You have no Saved Card.' ?></span>
    </div>
<?php endif ?>
<div class="actions-toolbar">
    <div class="primary">
        <button type="button" role="add-card"
                title="<?= $block->getMyAccountLabels('AC11') ?
                                $block->getMyAccountLabels('AC11') : 'Add New Card' ?>" 
                class="action primary add">
            <span>
                <?= $block->getMyAccountLabels('AC11') ?
                                $block->getMyAccountLabels('AC11') : 'Add New Card' ?>
            </span>
        </button>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "newcard": {
                "addCard": "button[role='add-card']",
                "addCardLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddNewCardLabel())) ?>",
                "isBilling": "<?= $block->escapeJs($block->escapeUrl($block->ifBillingAddressPresent())) ?>"
            }
        }
    }
</script>

